# drop/create functions to handle cleaning of phone numbers
DROP FUNCTION IF EXISTS ONLY_NUMBERS;
DELIMITER //
CREATE FUNCTION ONLY_NUMBERS(_STR VARCHAR(255)) RETURNS VARCHAR(20) DETERMINISTIC
    BEGIN
        DECLARE _NUMBERS VARCHAR(20);
        DECLARE _STR_POS BIGINT(20) DEFAULT 0;
        DECLARE _STR_ENDS BIGINT(20) DEFAULT 0;
        SET _STR_ENDS = CHAR_LENGTH(_STR);
        SET _NUMBERS = '';
        WHILE _STR_POS <= _STR_ENDS DO
            IF SUBSTR(_STR, _STR_POS, 1) REGEXP '^[0-9]$' THEN
                SET _NUMBERS = CONCAT(_NUMBERS, SUBSTR(_STR, _STR_POS, 1));
            END IF;
            SET _STR_POS = _STR_POS + 1;
        END WHILE;
        RETURN _NUMBERS;
    END //
DELIMITER ;
